import { DEMO_SHOP_SEEDS } from "./demo-seeds";
import type { MerchantTelemetry } from "./merchant-telemetry-types";
import { getSourceBundleRecord } from "./source-bundle";

const MERCHANT_TELEMETRY_FIXTURES: MerchantTelemetry[] = [
  {
    shop_id: "lei-kei-001",
    generated_at: "2026-08-09T08:00:00.000Z",
    exposure_events: [
      {
        id: "lei-kei-exposure-01",
        shop_id: "lei-kei-001",
        occurred_at: "2026-08-03T02:15:00.000Z",
        ip_address: "203.0.113.11",
        ip_visibility: "anonymized",
        referrer: "小紅書",
        device: "mobile",
        route: "/merchant",
        event_type: "impression",
      },
      {
        id: "lei-kei-exposure-02",
        shop_id: "lei-kei-001",
        occurred_at: "2026-08-04T04:40:00.000Z",
        ip_address: "198.51.100.22",
        ip_visibility: "anonymized",
        referrer: "澳門旅遊指南",
        device: "desktop",
        route: "/hunter",
        event_type: "detail_view",
      },
      {
        id: "lei-kei-exposure-03",
        shop_id: "lei-kei-001",
        occurred_at: "2026-08-05T03:05:00.000Z",
        ip_address: "203.0.113.33",
        ip_visibility: "anonymized",
        referrer: "Google 搜尋",
        device: "mobile",
        route: "/hunter",
        event_type: "save",
      },
      {
        id: "lei-kei-exposure-04",
        shop_id: "lei-kei-001",
        occurred_at: "2026-08-06T06:20:00.000Z",
        ip_address: "198.51.100.44",
        ip_visibility: "anonymized",
        referrer: "直接進入",
        device: "tablet",
        route: "/merchant",
        event_type: "impression",
      },
      {
        id: "lei-kei-exposure-05",
        shop_id: "lei-kei-001",
        occurred_at: "2026-08-07T09:10:00.000Z",
        ip_address: "203.0.113.55",
        ip_visibility: "anonymized",
        referrer: "小紅書",
        device: "mobile",
        route: "/hunter",
        event_type: "route_add",
      },
      {
        id: "lei-kei-exposure-06",
        shop_id: "lei-kei-001",
        occurred_at: "2026-08-08T01:50:00.000Z",
        ip_address: "198.51.100.66",
        ip_visibility: "anonymized",
        referrer: "Google 搜尋",
        device: "desktop",
        route: "/government",
        event_type: "detail_view",
      },
    ],
    sentiment_signals: [
      {
        id: "lei-kei-sentiment-01",
        shop_id: "lei-kei-001",
        occurred_at: "2026-08-03T05:00:00.000Z",
        channel: "小紅書",
        label: "positive",
        score: 0.8,
        excerpt: "The family story makes this stop memorable.",
        source_count: 18,
      },
      {
        id: "lei-kei-sentiment-02",
        shop_id: "lei-kei-001",
        occurred_at: "2026-08-04T05:00:00.000Z",
        channel: "Google 評論",
        label: "positive",
        score: 0.6,
        excerpt: "A welcoming traditional meal near the old streets.",
        source_count: 12,
      },
      {
        id: "lei-kei-sentiment-03",
        shop_id: "lei-kei-001",
        occurred_at: "2026-08-06T05:00:00.000Z",
        channel: "旅遊平台",
        label: "mixed",
        score: 0.2,
        excerpt: "Visitors want an easier way to find the shop story.",
        source_count: 9,
      },
      {
        id: "lei-kei-sentiment-04",
        shop_id: "lei-kei-001",
        occurred_at: "2026-08-08T05:00:00.000Z",
        channel: "小紅書",
        label: "positive",
        score: 0.7,
        excerpt: "Worth adding to a heritage walk.",
        source_count: 15,
      },
    ],
    publication: {
      platform: "xiaohongshu",
      status: "draft",
      post_id: null,
      created_at: "2026-08-08T08:00:00.000Z",
      published_at: null,
      metrics: { impressions: 0, saves: 0, comments: 0 },
    },
  },
  {
    shop_id: "sun-fong-002",
    generated_at: "2026-08-09T08:00:00.000Z",
    exposure_events: [
      {
        id: "sun-fong-exposure-01",
        shop_id: "sun-fong-002",
        occurred_at: "2026-08-03T02:30:00.000Z",
        ip_address: "203.0.113.71",
        ip_visibility: "anonymized",
        referrer: "小紅書",
        device: "mobile",
        route: "/merchant",
        event_type: "impression",
      },
      {
        id: "sun-fong-exposure-02",
        shop_id: "sun-fong-002",
        occurred_at: "2026-08-04T04:20:00.000Z",
        ip_address: "198.51.100.72",
        ip_visibility: "anonymized",
        referrer: "澳門旅遊指南",
        device: "desktop",
        route: "/hunter",
        event_type: "detail_view",
      },
      {
        id: "sun-fong-exposure-03",
        shop_id: "sun-fong-002",
        occurred_at: "2026-08-05T03:45:00.000Z",
        ip_address: "203.0.113.73",
        ip_visibility: "anonymized",
        referrer: "Google 搜尋",
        device: "mobile",
        route: "/hunter",
        event_type: "save",
      },
      {
        id: "sun-fong-exposure-04",
        shop_id: "sun-fong-002",
        occurred_at: "2026-08-06T06:10:00.000Z",
        ip_address: "198.51.100.74",
        ip_visibility: "anonymized",
        referrer: "直接進入",
        device: "tablet",
        route: "/merchant",
        event_type: "impression",
      },
      {
        id: "sun-fong-exposure-05",
        shop_id: "sun-fong-002",
        occurred_at: "2026-08-07T09:25:00.000Z",
        ip_address: "203.0.113.75",
        ip_visibility: "anonymized",
        referrer: "小紅書",
        device: "mobile",
        route: "/hunter",
        event_type: "route_add",
      },
      {
        id: "sun-fong-exposure-06",
        shop_id: "sun-fong-002",
        occurred_at: "2026-08-08T01:35:00.000Z",
        ip_address: "198.51.100.76",
        ip_visibility: "anonymized",
        referrer: "Google 搜尋",
        device: "desktop",
        route: "/government",
        event_type: "detail_view",
      },
    ],
    sentiment_signals: [
      {
        id: "sun-fong-sentiment-01",
        shop_id: "sun-fong-002",
        occurred_at: "2026-08-03T05:00:00.000Z",
        channel: "小紅書",
        label: "positive",
        score: 0.9,
        excerpt: "The traditional drinks are a reliable local recommendation.",
        source_count: 24,
      },
      {
        id: "sun-fong-sentiment-02",
        shop_id: "sun-fong-002",
        occurred_at: "2026-08-04T05:00:00.000Z",
        channel: "Google 評論",
        label: "positive",
        score: 0.8,
        excerpt: "A classic tea stop with kind service.",
        source_count: 20,
      },
      {
        id: "sun-fong-sentiment-03",
        shop_id: "sun-fong-002",
        occurred_at: "2026-08-06T05:00:00.000Z",
        channel: "旅遊平台",
        label: "positive",
        score: 0.7,
        excerpt: "Easy to include in a short Macau visit.",
        source_count: 11,
      },
      {
        id: "sun-fong-sentiment-04",
        shop_id: "sun-fong-002",
        occurred_at: "2026-08-08T05:00:00.000Z",
        channel: "小紅書",
        label: "positive",
        score: 0.8,
        excerpt: "A calm break from the busy main streets.",
        source_count: 17,
      },
    ],
    publication: {
      platform: "xiaohongshu",
      status: "published",
      post_id: "demo-sun-fong-20260801",
      created_at: "2026-08-01T08:00:00.000Z",
      published_at: "2026-08-01T09:00:00.000Z",
      metrics: { impressions: 132, saves: 21, comments: 8 },
    },
  },
  {
    shop_id: "tak-hing-003",
    generated_at: "2026-08-09T08:00:00.000Z",
    exposure_events: [
      {
        id: "tak-hing-exposure-01",
        shop_id: "tak-hing-003",
        occurred_at: "2026-08-03T02:05:00.000Z",
        ip_address: "203.0.113.81",
        ip_visibility: "anonymized",
        referrer: "小紅書",
        device: "mobile",
        route: "/merchant",
        event_type: "impression",
      },
      {
        id: "tak-hing-exposure-02",
        shop_id: "tak-hing-003",
        occurred_at: "2026-08-04T04:55:00.000Z",
        ip_address: "198.51.100.82",
        ip_visibility: "anonymized",
        referrer: "澳門旅遊指南",
        device: "desktop",
        route: "/hunter",
        event_type: "detail_view",
      },
      {
        id: "tak-hing-exposure-03",
        shop_id: "tak-hing-003",
        occurred_at: "2026-08-05T03:25:00.000Z",
        ip_address: "203.0.113.83",
        ip_visibility: "anonymized",
        referrer: "Google 搜尋",
        device: "mobile",
        route: "/hunter",
        event_type: "save",
      },
      {
        id: "tak-hing-exposure-04",
        shop_id: "tak-hing-003",
        occurred_at: "2026-08-06T06:45:00.000Z",
        ip_address: "198.51.100.84",
        ip_visibility: "anonymized",
        referrer: "直接進入",
        device: "tablet",
        route: "/merchant",
        event_type: "impression",
      },
      {
        id: "tak-hing-exposure-05",
        shop_id: "tak-hing-003",
        occurred_at: "2026-08-07T09:40:00.000Z",
        ip_address: "203.0.113.85",
        ip_visibility: "anonymized",
        referrer: "小紅書",
        device: "mobile",
        route: "/hunter",
        event_type: "route_add",
      },
      {
        id: "tak-hing-exposure-06",
        shop_id: "tak-hing-003",
        occurred_at: "2026-08-08T01:15:00.000Z",
        ip_address: "198.51.100.86",
        ip_visibility: "anonymized",
        referrer: "Google 搜尋",
        device: "desktop",
        route: "/government",
        event_type: "detail_view",
      },
    ],
    sentiment_signals: [
      {
        id: "tak-hing-sentiment-01",
        shop_id: "tak-hing-003",
        occurred_at: "2026-08-03T05:00:00.000Z",
        channel: "小紅書",
        label: "positive",
        score: 0.6,
        excerpt: "Visitors admire the handmade craft.",
        source_count: 14,
      },
      {
        id: "tak-hing-sentiment-02",
        shop_id: "tak-hing-003",
        occurred_at: "2026-08-04T05:00:00.000Z",
        channel: "Google 評論",
        label: "mixed",
        score: 0.1,
        excerpt: "The craft is strong, but opening information varies.",
        source_count: 10,
      },
      {
        id: "tak-hing-sentiment-03",
        shop_id: "tak-hing-003",
        occurred_at: "2026-08-06T05:00:00.000Z",
        channel: "旅遊平台",
        label: "mixed",
        score: 0.2,
        excerpt: "A worthwhile stop when visitors can confirm the hours.",
        source_count: 8,
      },
      {
        id: "tak-hing-sentiment-04",
        shop_id: "tak-hing-003",
        occurred_at: "2026-08-08T05:00:00.000Z",
        channel: "小紅書",
        label: "positive",
        score: 0.5,
        excerpt: "A distinctive local snack with a careful process.",
        source_count: 12,
      },
    ],
    publication: {
      platform: "xiaohongshu",
      status: "confirmed",
      post_id: "demo-tak-hing-20260806",
      created_at: "2026-08-06T08:00:00.000Z",
      published_at: null,
      metrics: { impressions: 0, saves: 0, comments: 0 },
    },
  },
];

export function getMerchantTelemetry(shopId?: string): MerchantTelemetry {
  const fixture = MERCHANT_TELEMETRY_FIXTURES.find((telemetry) => telemetry.shop_id === shopId);
  if (fixture) return fixture;

  const source = getSourceBundleRecord(shopId);
  if (source) {
    return {
      shop_id: source.shop_id,
      generated_at: "2026-08-09T08:00:00.000Z",
      exposure_events: [],
      sentiment_signals: [],
      publication: {
        platform: source.merchant.publication.platform,
        status: source.merchant.publication.status,
        post_id: null,
        created_at: "2026-08-09T08:00:00.000Z",
        published_at: null,
        metrics: {
          impressions: source.merchant.publication.metrics.impressions ?? 0,
          saves: source.merchant.publication.metrics.saves ?? 0,
          comments: source.merchant.publication.metrics.comments ?? 0,
        },
      },
    };
  }

  const fallbackShopId = DEMO_SHOP_SEEDS[0]?.shop_id;

  return (
    MERCHANT_TELEMETRY_FIXTURES.find((telemetry) => telemetry.shop_id === fallbackShopId) ??
    MERCHANT_TELEMETRY_FIXTURES[0]
  );
}
